import assert from 'node:assert/strict';
import {parseRestaurantCommand,normalizeVoice} from '../public/voice-engine.js';
let n=0;const eq=(a,b,msg)=>{assert.equal(a,b,msg);n++};
const cmd=(s,c={})=>parseRestaurantCommand(s,c);
eq(normalizeVoice('Équipe – À table !'),'equipe a table','normalisation');
eq(cmd('table 12 addition').intent,'TABLE_BILL_REQUEST');eq(cmd('table 12 addition').entities.tableId,12);
eq(cmd('table douze, deux eaux').intent,'KITCHEN_TICKET');eq(cmd('table douze, deux eaux').entities.tableId,12);eq(cmd('table douze, deux eaux').entities.items,'deux eaux');
eq(cmd('table vingt deux servie').entities.tableId,22);eq(cmd('table vingt deux servie').entities.status,'served');
eq(cmd('table 3 allergie arachides').requiresConfirmation,true);eq(cmd('table 3 allergie arachides').entities.allergy,'arachides');
eq(cmd('reserve quatre personnes a 20 h').intent,'RESERVATION_CREATE');eq(cmd('reserve quatre personnes a 20 h').entities.people,4);eq(cmd('reserve quatre personnes a 20 h').entities.time,'20:00');
eq(cmd('rupture saumon').intent,'STOCK_OUT');eq(cmd('rupture saumon').entities.product,'saumon');
eq(cmd('stock saumon 3').intent,'STOCK_SET');eq(cmd('stock saumon 3').entities.quantity,3);eq(cmd('stock saumon trois').entities.quantity,3);
eq(cmd('retire deux saumons du stock').intent,'STOCK_SUBTRACT');eq(cmd('retire deux saumons du stock').requiresConfirmation,true);
eq(cmd('ajoute une tache nettoyer terrasse').intent,'TASK_CREATE');eq(cmd('ajoute une tache nettoyer terrasse').entities.task,'nettoyer terrasse');
eq(cmd('Fatou absente aujourd hui').intent,'TEAM_ABSENCE');eq(cmd('Fatou absente aujourd hui').requiresConfirmation,true);
eq(cmd('commande table 5 prete').intent,'ORDER_STATUS');eq(cmd('commande table 5 prete').entities.status,'ready');
eq(cmd('ouvre la caisse').entities.section,'cash');eq(cmd('ouvre les recettes').entities.section,'recipes');eq(cmd('ouvre le planning').entities.section,'planning');
eq(cmd('elle veut l addition',{tableId:7}).entities.tableId,7);eq(cmd('supprime tout').intent,'DANGEROUS_BLOCKED');
console.log(`restaurant-core: ${n} assertions PASS`);